global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "service-courier"
    metrics_path: /metrics
    static_configs:
      - targets: ["service-courier:8080"]

  # - job_name: "service-courier-worker"
  #   metrics_path: /metrics
  #   static_configs:
  #     - targets: ["service-courier-worker:9091"]